name: test
on:
  - workflow_call
jobs:
  test:
    strategy:
      matrix:
        os: ['ubuntu-latest']
        node-version: [14.x, 16.x]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@master
        with:
          run_install: true
      - uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - run: pnpm build
      - run: pnpm test
